import zotova1 from './assets/projects/zotova-1.jpg'
import zotova2 from './assets/projects/zotova-2.jpg'
import zotova3 from './assets/projects/zotova-3.jpg'
import medequip1 from './assets/projects/medequip-1.jpg'
import medequip2 from './assets/projects/medequip-2.jpg'
import medequip3 from './assets/projects/medequip-3.jpg'
import uteam1 from './assets/projects/uteam-1.jpg'
import uteam2 from './assets/projects/uteam-2.jpg'
import uteam3 from './assets/projects/uteam-3.jpg'
import ccc1 from './assets/projects/ccc-1.jpg'
import ccc2 from './assets/projects/ccc-2.jpg'
import ccc3 from './assets/projects/ccc-3.jpg'
import ramki1 from './assets/projects/ramki-1.jpg'
import ramki2 from './assets/projects/ramki-2.jpg'
import ramki3 from './assets/projects/ramki-3.jpg'
import dreamy1 from './assets/projects/dreamy-1.jpg'
import dreamy2 from './assets/projects/dreamy-2.jpg'
import dreamy3 from './assets/projects/dreamy-3.jpg'

const shared = {
  logo: 'DB',
  skills: [
    { name: 'TypeScript', level: 5 },
    { name: 'React',      level: 5 },
    { name: 'Next.js',    level: 4 },
    { name: 'Node.js',    level: 4 },
    { name: 'REST API',   level: 5 },
    { name: 'Git',        level: 5 },
    { name: 'PostgreSQL', level: 3 },
    { name: 'Docker',     level: 3 },
    { name: 'Redis',      level: 3 },
    { name: 'GraphQL',    level: 3 },
    { name: 'Linux',      level: 3 },
    { name: 'WordPress',  level: 4 },
  ],
  socials: {
    telegram: 'https://t.me/unemployment_78',
    email: 'dbotyangroup@gmail.com',
  },
  projects: [
    {
      number: '001',
      title: 'Anastasiia Zotova - Portfolio',
      stack: ['React', 'TypeScript', 'Vite', 'CSS'],
      live: 'https://byanaz.vercel.app',
      images: [zotova1, zotova2, zotova3],
    },
    {
      number: '002',
      title: 'DreamyVoice',
      stack: ['Next.js', 'TypeScript', 'Prisma', 'pnpm'],
      live: 'https://dreamyvoice.net',
      images: [dreamy1, dreamy2, dreamy3],
    },
    {
      number: '003',
      title: 'unemployment.team',
      stack: ['Next.js', 'TypeScript', 'Tailwind', 'Node.js'],
      live: 'https://unemployment.team',
      images: [uteam1, uteam2, uteam3],
    },
    {
      number: '004',
      title: 'МедЭквип',
      stack: ['Next.js', 'TypeScript', 'Tailwind', 'Node.js'],
      live: 'https://med-equipment-homepage.vercel.app',
      images: [medequip1, medequip2, medequip3],
      template: true,
    },
    {
      number: '005',
      title: 'Журнал РАМКИ',
      stack: ['WordPress', 'Elementor', 'PHP', 'Bun'],
      live: 'https://ramki-magazine.ru',
      images: [ramki1, ramki2, ramki3],
    },
    {
      number: '006',
      title: 'Центр Целостности Человека',
      stack: ['WordPress', 'ACF', 'WooCommerce', 'PHP'],
      live: '#',
      images: [ccc1, ccc2, ccc3],
    },
  ],
}

const socialLinks = [
  { label: 'Telegram', href: shared.socials.telegram, icon: 'telegram' as const },
  { label: 'Email', href: `mailto:${shared.socials.email}`, icon: 'mail' as const },
]

export const content = {
  ru: {
    nav: {
      logo: shared.logo,
      links: [
        { label: 'Проекты', href: '#projects' },
        { label: 'Услуги', href: '#services' },
        { label: 'Калькулятор', href: '#calculator' },
        { label: 'Обо мне', href: '#about' },
        { label: 'Опыт', href: '#experience' },
        { label: 'Блог', href: '/blog' },
        { label: 'FAQ', href: '#faq' },
        { label: 'Контакт', href: '#contact' },
      ],
    },
    hero: {
      badge: 'web разработчик',
      name: { first: 'Дмитрий', last: 'Ботян' },
      description: 'Пишу код, который решает реальные задачи. Берусь за проект целиком: от первого коммита до деплоя на прод.',
      buttons: { contact: 'Связаться', projects: 'Проекты' },
      socials: shared.socials,
      socialLinks,
    },
    about: {
      sectionLabel: '01 - About',
      heading: 'Кто я',
      paragraphs: [
        'Занимаюсь разработкой уже несколько лет. Начинал с фронтенда, сейчас закрываю и бэк, и деплой. Работаю в основном с небольшими командами и стартапами.',
        'Мне интереснее всего проекты, где есть реальная задача, а не просто "сделать сайт". Если в брифе написано "хочу как у конкурентов" - это не про меня.',
        'Читаю про архитектуру систем, слежу за тем, что происходит в вебе. Иногда пишу заметки про то, что узнал.',
      ],
      stats: [
        { value: '3+', label: 'года опыта' },
        { value: '20+', label: 'проектов' },
        { value: '15+', label: 'клиентов' },
      ],
      stackLabel: 'Стек',
      skills: shared.skills,
      hobbiesLabel: 'Увлечения',
      hobbies: [
        { icon: 'Music', label: 'Музыка' },
        { icon: 'Plane', label: 'Путешествия' },
        { icon: 'BookOpen', label: 'Чтение' },
        { icon: 'Palette', label: 'Дизайн' },
      ],
    },
    experience: {
      sectionLabel: '03 - Experience',
      heading: 'Опыт',
      items: [
        {
          period: '2025 - н.в.', role: 'Co-founder / Fullstack Developer', company: 'unemployment.team',
          description: 'Со-основали unemployment.team вместе с Артёмом. Занимаюсь архитектурой, разработкой и общением с клиентами. Пишем на React, Next.js, TypeScript, иногда Node.js на бэке.',
          tags: ['React', 'Next.js', 'TypeScript', 'Node.js', 'UI/UX'],
        },
        {
          period: '2023 - н.в.', role: 'Full-stack Developer', company: 'Freelance',
          description: 'Брал проекты напрямую: лендинги, интернет-магазины, корпоративные сайты, небольшие веб-приложения. WordPress, React или Next.js в зависимости от задачи.',
          tags: ['React', 'Next.js', 'WordPress', 'Node.js'],
        },
        {
          period: '2022 - 2023', role: 'Frontend Developer', company: 'Digital Agency',
          description: 'Делал интерфейсы для b2b-клиентов в небольшом агентстве. Там же начал нормально разбираться в code review и перформансе.',
          tags: ['React', 'TypeScript', 'Figma'],
        },
        {
          period: '2021 - 2022', role: 'Junior Developer', company: 'Startup',
          description: 'Первый коммерческий опыт. С нуля написали SaaS для управления задачами, я отвечал за фронтенд.',
          tags: ['JavaScript', 'Node.js', 'PostgreSQL'],
        },
      ],
    },
    projects: {
      sectionLabel: '02 - Projects',
      heading: 'Последние проекты',
      templateBadge: 'Шаблон',
      templateNote: 'Готовый шаблон, могу адаптировать под вашу компанию: контент, бренд, доменные страницы. Сроки и стоимость ниже, чем у проекта с нуля.',
      items: [
        { ...shared.projects[0], description: 'Персональное портфолио для бренд-менеджера. Яркий дизайн, скрапбукинг-эстетика, анимации.' },
        { ...shared.projects[1], description: 'Платформа для команды аниме-озвучки. Каталог тайтлов, страницы релизов с плеером, избранное, рандом, админка для редакторов. Next.js, Prisma, PostgreSQL.' },
        { ...shared.projects[2], description: 'Сайт нашей команды. Услуги, портфолио, блог, многошаговая форма заявки.' },
        { ...shared.projects[3], description: 'Корпоративный сайт поставщика медоборудования. Каталог продукции, страницы решений по сегментам, форма запроса цены.' },
        { ...shared.projects[4], description: 'Деловой онлайн-журнал. Кастомная тема на WordPress, конструктор страниц Elementor, архив выпусков, экосистема разделов и подписка на рассылку.' },
        { ...shared.projects[5], description: 'Сайт центра холистической медицины. Кастомные типы записей и поля на ACF, WooCommerce-магазин товаров, многошаговая форма записи на приём, блог.' },
      ],
    },
    team: {
      heading: 'Наша команда',
      name: 'unemployment.team',
      description: 'unemployment.team - это я и Артём. Назвали так потому что оба бросили обычную работу ради своих проектов. Закрываем всё: дизайн, разработку, деплой, поддержку.',
      siteLabel: 'Перейти на сайт команды',
      siteUrl: 'https://unemployment.team/en',
      availableLabel: 'Открыты для новых проектов',
      members: [
        {
          name: 'Дмитрий Ботян',
          role: 'Fullstack Developer',
          tag: 'Со-основатель',
          description: 'Разбираюсь в том, как это должно работать, и пишу код. Отвечаю за архитектуру и клиентскую часть проектов.',
        },
        {
          name: 'Артём Тодор',
          role: 'Fullstack Developer',
          tag: 'Со-основатель',
          description: 'Занимается серверами, деплоем, настройкой окружений. Если что-то падает в 3 ночи, это к нему.',
        },
      ],
      services: ['Web Development', 'UI/UX Design', 'Tech Support'],
    },
    testimonials: {
      heading: 'Отзывы',
      items: [
        {
          text: 'Замечательный специалист! Сделал всё быстро и качественно. Всегда был на связи и отвечал на любые вопросы.',
          name: 'Елизавета',
          role: 'Разработка сайта',
          initials: 'Е',
        },
        {
          text: 'Делал сайт для просмотра аниме. Дмитрий взялся сделать всё в кратчайшие сроки, это здорово!',
          name: 'Денис',
          role: 'Сайт для аниме',
          initials: 'Д',
        },
        {
          text: 'Отличный специалист! Выполнил задачу в оговорённый срок. Реализовал все пожелания и устранил все правки.',
          name: 'Андрей',
          role: 'Разработка сайта',
          initials: 'А',
        },
        {
          text: 'Собрал готовый сайт по моим материалам и брифу. Получила демо, потом оплатила и забрала полную версию.',
          name: 'Мария',
          role: 'Сайт по брифу',
          initials: 'М',
        },
        {
          text: 'Нужен был корпоративный сайт с интеграцией CRM. Дмитрий сделал всё идеально: в срок, с тестированием, мелкие правки учёл.',
          name: 'Сергей',
          role: 'Корпоративный сайт',
          initials: 'С',
        },
        {
          text: 'Заказывала лендинг для продажи хендмейда. Реализовал всё точно по ТЗ и предложил полезные идеи по улучшению.',
          name: 'Ольга',
          role: 'Лендинг',
          initials: 'О',
        },
        {
          text: 'Сделал интернет-магазин с нуля. Учёл все мои пожелания по дизайну и функционалу, предложил оптимальные решения.',
          name: 'Анна',
          role: 'Интернет-магазин',
          initials: 'А',
        },
        {
          text: 'Заказывал телеграм-бота для приёма заявок. Дмитрий быстро вник в задачу и сделал бота с админкой, которым реально удобно пользоваться.',
          name: 'Павел',
          role: 'Telegram-бот',
          initials: 'П',
        },
        {
          text: 'Обновил мой старый сайт: новый дизайн, грузиться стал заметно быстрее. Позиции в поиске не просели, как я боялась.',
          name: 'Екатерина',
          role: 'Редизайн',
          initials: 'Е',
        },
        {
          text: 'Подхватил проект после другого разработчика. Разобрался в чужом коде, починил баги и довёл всё до ума.',
          name: 'Никита',
          role: 'Доработка сайта',
          initials: 'Н',
        },
        {
          text: 'Сделал лендинг на Tilda с кастомными блоками. Получилось не как у всех, и форму сразу связал с CRM.',
          name: 'Виктория',
          role: 'Сайт на Tilda',
          initials: 'В',
        },
        {
          text: 'Настроил интеграцию сайта с Wildberries и Ozon. Остатки теперь обновляются сами, перестал терять заказы.',
          name: 'Роман',
          role: 'Интеграция',
          initials: 'Р',
        },
        {
          text: 'Веду сайт у Дмитрия на поддержке. Отвечает быстро, правки вносит в тот же день, всё под контролем.',
          name: 'Дарья',
          role: 'Обслуживание сайта',
          initials: 'Д',
        },
      ],
    },
    faq: {
      heading: 'Частые вопросы',
      items: [
        {
          q: 'Сколько времени занимает разработка?',
          a: 'Зависит от задачи. Лендинг делаю за 1-2 недели. Полноценное приложение от месяца и больше. В начале всегда говорю реальные сроки, не занижаю.',
        },
        {
          q: 'Работаете с дизайном или только с кодом?',
          a: 'Могу взять готовый дизайн из Figma или придумать сам. Понимаю как должно выглядеть, так что просто вёрстки не будет.',
        },
        {
          q: 'Как вы берёте оплату?',
          a: 'Обычно 50% в начале, 50% по итогу. Для длинных проектов помесячно. Работаю официально, договор оформляю.',
        },
        {
          q: 'Как вы общаетесь в процессе работы?',
          a: 'Через Telegram или почту. Раз в несколько дней пишу что сделано, показываю промежуточный результат. Не пропадаю.',
        },
        {
          q: 'Что происходит после сдачи проекта?',
          a: 'После сдачи есть период поддержки. Если что-то всплывёт - пофикшу. Могу помочь с хостингом и документацией.',
        },
      ],
    },
    contact: {
      sectionLabel: '05 - Contact',
      heading: 'Напишите мне',
      subheading: 'Есть проект или идея? Напишите, отвечаю в течение дня.',
      form: {
        nameLabel: 'Имя', namePlaceholder: 'Ваше имя',
        emailLabel: 'Email', emailPlaceholder: 'your@email.com',
        messageLabel: 'Сообщение', messagePlaceholder: 'Расскажите о своём проекте...',
        submitIdle: 'Отправить', submitSending: 'Отправка...', submitSent: '✓ Отправлено',
        consentBefore: 'Я ознакомлен с ',
        consentPrivacy: 'Политикой конфиденциальности',
        consentMiddle: ' и даю ',
        consentConsent: 'согласие на обработку персональных данных',
        consentAfter: '.',
        consentRequired: 'Для отправки сообщения необходимо принять условия обработки персональных данных.',
        submitError: 'Не удалось отправить. Попробуйте ещё раз или напишите в Telegram.',
        recaptchaBefore: 'Защищено reCAPTCHA. Применяются ',
        recaptchaPrivacy: 'Политика конфиденциальности',
        recaptchaMiddle: ' и ',
        recaptchaTerms: 'Условия использования',
        recaptchaAfter: ' Google.',
      },
      directLabel: 'Или напрямую',
      email: shared.socials.email,
      socialsLabel: 'Контакты',
      socials: socialLinks,
      availabilityLabel: 'Доступность',
      availabilityText: 'Открыт к новым проектам',
    },
    services: {
      heading: 'Услуги и цены',
      subheading: 'Прозрачные тарифы на разработку сайтов, ботов и интеграций. Цены - на 2026 год.',
      popularBadge: 'Популярный',
      currency: '₽',
      thousand: 'тыс.',
      fromLabel: 'от',
      ctaPackage: 'Обсудить пакет',
      tiers: [
        {
          id: 'start',
          name: 'Старт',
          priceFrom: 35,
          priceTo: 80,
          tagline: 'Для быстрого выхода в онлайн',
          description: 'Если нужно срочно запустить присутствие в сети - лендинг, сайт-визитка или простой бот.',
          includes: [
            'Лендинг, сайт на Tilda или простой Telegram-бот',
            'До 5 экранов / разделов',
            'Адаптивная вёрстка под мобильные',
            'Базовая SEO-оптимизация',
            'Подключение домена и аналитики',
            'Запуск за 1–2 недели',
            '14 дней техподдержки',
          ],
          popular: false,
        },
        {
          id: 'business',
          name: 'Бизнес',
          priceFrom: 80,
          priceTo: 160,
          tagline: 'Оптимальный выбор для роста',
          description: 'Полноценный корпоративный сайт, магазин на WordPress или Telegram-бот с веб-админкой.',
          includes: [
            'Корпоративный сайт (5–15 страниц), магазин на WP или бот с админкой',
            'Кастомный дизайн под бренд',
            'Расширенная SEO-оптимизация',
            'Интеграция с CRM или платежами',
            'Подключение аналитики и пикселей',
            'Запуск за 3–6 недель',
            '30 дней техподдержки',
          ],
          popular: true,
        },
        {
          id: 'premium',
          name: 'Премиум',
          priceFrom: 150,
          priceTo: 350,
          tagline: 'Сложные проекты под ключ',
          description: 'Интернет-магазин на Next.js, маркетплейс или платформа с интеграциями и абонентским обслуживанием.',
          includes: [
            'Магазин на Next.js, маркетплейс или SaaS-платформа',
            'Уникальный дизайн + UX-исследование',
            'Интеграции: Wildberries, Ozon, 1С, CRM, платежи',
            'Расширенная SEO + микроразметка',
            'Скорость 90+ по PageSpeed',
            'Запуск за 6–12 недель',
            '3 месяца техподдержки + обучение',
          ],
          popular: false,
        },
      ],
    },
    calculator: {
      heading: 'Рассчитайте стоимость',
      subheading: 'Примерная вилка цен по вашему проекту. Точную сумму назову после короткого брифа.',
      typeLabel: 'Что нужно сделать',
      pagesLabel: 'Количество страниц / разделов',
      pagesHint: 'Каждая дополнительная страница - +5 тыс. ₽',
      designLabel: 'Дизайн',
      extrasLabel: 'Дополнительные опции',
      resultLabel: 'Примерная стоимость',
      resultPrefix: 'от',
      resultDivider: 'до',
      currency: '₽',
      thousand: 'тыс. ₽',
      noteTitle: 'Это предварительная оценка',
      noteText: 'Финальная цена обсуждается после брифа. Готов сделать дешевле, если возьму проект целиком от и до.',
      ctaLabel: 'Получить точный расчёт',
      resetLabel: 'Сбросить',
      types: [
        { id: 'landing', label: 'Лендинг' },
        { id: 'corporate', label: 'Корпоративный сайт' },
        { id: 'shopNext', label: 'Магазин на Next.js' },
        { id: 'shopWp', label: 'Магазин на WordPress' },
        { id: 'tilda', label: 'Сайт на Tilda' },
        { id: 'botAdmin', label: 'Бот + админка' },
        { id: 'botSimple', label: 'Простой бот' },
        { id: 'redesign', label: 'Редизайн' },
      ],
      designs: [
        { id: 'template', label: 'Готовый шаблон', mult: 0.85 },
        { id: 'figma', label: 'Готовый дизайн в Figma', mult: 1.0 },
        { id: 'custom', label: 'Заказной дизайн', mult: 1.3 },
      ],
      extras: [
        { id: 'seo', label: 'SEO-настройка под ключ', price: 15000 },
        { id: 'copy', label: 'Копирайтинг текстов', price: 20000 },
        { id: 'integrations', label: 'Интеграции (CRM, оплата, маркетплейсы)', price: 35000 },
        { id: 'multilang', label: 'Мультиязычность', price: 25000 },
        { id: 'support', label: 'Абонентское обслуживание (1 мес)', price: 30000 },
        { id: 'analytics', label: 'Настройка аналитики и пикселей', price: 10000 },
      ],
    },
    blog: {
      heading: 'Блог',
      subheading: 'Пишу о разработке, ценах и технологиях простым языком. Без воды и продаж.',
      allLabel: 'Все статьи',
      readLabel: 'Читать',
      backLabel: 'Все статьи',
      homeLabel: 'Главная',
      tocLabel: 'Содержание',
      faqLabel: 'Частые вопросы',
      relatedLabel: 'Читайте также',
      ctaTitle: 'Нужен сайт или доработка?',
      ctaText: 'Расскажу о сроках и ценах под вашу задачу. Отвечу в течение часа.',
      ctaCalc: 'Рассчитать стоимость',
      ctaContact: 'Связаться',
      indexTitle: 'Блог о разработке сайтов и ботов',
      indexSubheading: 'Статьи о ценах, технологиях и продвижении сайтов. Опыт из реальных проектов.',
      minRead: 'мин чтения',
    },
    cookies: {
      heading: 'Сайт использует cookie',
      text: 'Мы собираем обезличенные данные о посещениях, чтобы понимать, как улучшать сайт. Продолжая использование, вы соглашаетесь с обработкой данных.',
      privacyLink: 'Политика конфиденциальности',
      accept: 'Принять',
      decline: 'Отказаться',
    },
    popup: {
      heading: 'Нужен сайт или доработка?',
      subheading: 'Отвечу в течение часа',
      description: 'Расскажу о сроках, ценах и помогу выбрать стек. Без обязательств.',
      ctaCalculate: 'Рассчитать стоимость',
      ctaTelegram: 'Написать в Telegram',
      closeLabel: 'Закрыть',
    },
    floatingCta: {
      label: 'Получить расчёт',
      shortLabel: 'Расчёт',
      ariaLabel: 'Перейти к калькулятору стоимости',
    },
    footer: {
      author: 'Дмитрий Ботян',
      role: 'web разработчик',
      builtWith: 'React + Vite + RetroUI',
      links: socialLinks,
      legalLinks: {
        privacy: 'Политика конфиденциальности',
        terms: 'Пользовательское соглашение',
        consent: 'Согласие на обработку персональных данных',
      },
    },
  },
  en: {
    nav: {
      logo: shared.logo,
      links: [
        { label: 'Projects', href: '#projects' },
        { label: 'Services', href: '#services' },
        { label: 'Calculator', href: '#calculator' },
        { label: 'About', href: '#about' },
        { label: 'Experience', href: '#experience' },
        { label: 'Blog', href: '/blog' },
        { label: 'FAQ', href: '#faq' },
        { label: 'Contact', href: '#contact' },
      ],
    },
    hero: {
      badge: 'web developer',
      name: { first: 'Dmitry', last: 'Botyan' },
      description: 'I write code that solves real problems. I take ownership of the whole thing: from the first commit to production.',
      buttons: { contact: 'Get in touch', projects: 'Projects' },
      socials: shared.socials,
      socialLinks,
    },
    about: {
      sectionLabel: '01 - About',
      heading: 'Who I am',
      paragraphs: [
        "I've been doing this for a few years now. Started with frontend, picked up backend and DevOps along the way. I mostly work with small teams and startups.",
        "I'm most interested in projects where there's an actual problem to solve, not just 'make us a website'. If the brief says 'we want something like our competitors' - that's not really my thing.",
        "I read about systems architecture and keep up with what's happening in web dev. Sometimes I write notes for myself about things I figured out.",
      ],
      stats: [
        { value: '3+', label: 'years exp.' },
        { value: '20+', label: 'projects' },
        { value: '15+', label: 'clients' },
      ],
      stackLabel: 'Stack',
      skills: shared.skills,
      hobbiesLabel: 'Hobbies',
      hobbies: [
        { icon: 'Music', label: 'Music' },
        { icon: 'Plane', label: 'Travelling' },
        { icon: 'BookOpen', label: 'Reading' },
        { icon: 'Palette', label: 'Design' },
      ],
    },
    experience: {
      sectionLabel: '03 - Experience',
      heading: 'Experience',
      items: [
        {
          period: '2025 - present', role: 'Co-founder / Fullstack Developer', company: 'unemployment.team',
          description: "Co-founded unemployment.team with Artem. I handle architecture, development, and client communication. We build with React, Next.js, TypeScript, and Node.js on the backend.",
          tags: ['React', 'Next.js', 'TypeScript', 'Node.js', 'UI/UX'],
        },
        {
          period: '2023 - present', role: 'Full-stack Developer', company: 'Freelance',
          description: 'Took direct client projects: landing pages, e-commerce sites, corporate websites, small web apps. WordPress, React, or Next.js depending on what made sense.',
          tags: ['React', 'Next.js', 'WordPress', 'Node.js'],
        },
        {
          period: '2022 - 2023', role: 'Frontend Developer', company: 'Digital Agency',
          description: "Built interfaces for B2B clients at a small agency. That's where I got serious about code reviews and performance.",
          tags: ['React', 'TypeScript', 'Figma'],
        },
        {
          period: '2021 - 2022', role: 'Junior Developer', company: 'Startup',
          description: 'First commercial job. We built a SaaS task management app from scratch; I handled the frontend.',
          tags: ['JavaScript', 'Node.js', 'PostgreSQL'],
        },
      ],
    },
    projects: {
      sectionLabel: '02 - Projects',
      heading: 'Latest projects',
      templateBadge: 'Template',
      templateNote: 'Ready-made template. I can adapt it to your company: content, branding, domain-specific pages. Cheaper and faster than building from scratch.',
      items: [
        { ...shared.projects[0], description: 'Personal portfolio for a brand manager. Vivid scrapbook aesthetic, rich animations.' },
        { ...shared.projects[1], description: 'Platform for an anime dubbing team. Title catalog, release pages with player, favorites, random pick, editor admin panel. Next.js, Prisma, PostgreSQL.' },
        { ...shared.projects[2], description: "Our team's website. Services, portfolio, blog, multi-step project request form." },
        { ...shared.projects[3], description: 'Corporate site for a medical equipment supplier. Product catalog, solution pages by segment, price request form.' },
        { ...shared.projects[4], description: 'Business online magazine. Custom WordPress theme, Elementor page builder, issue archive, multi-section ecosystem, newsletter signup.' },
        { ...shared.projects[5], description: 'Holistic medicine center website. Custom post types and fields via ACF, WooCommerce shop, multi-step booking form, blog.' },
      ],
    },
    team: {
      heading: 'Our team',
      name: 'unemployment.team',
      description: "unemployment.team is me and Artem. We named it that because we both quit regular jobs to do our own thing. We cover everything: design, development, deployment, support.",
      siteLabel: 'Visit team website',
      siteUrl: 'https://unemployment.team/en',
      availableLabel: 'Available for new projects',
      members: [
        {
          name: 'Dmitry Botyan',
          role: 'Fullstack Developer',
          tag: 'Co-founder',
          description: 'I figure out how things should work and write the code. Architecture and client-facing parts are on me.',
        },
        {
          name: 'Artem Todor',
          role: 'Fullstack Developer',
          tag: 'Co-founder',
          description: "He handles servers, deployments, and environments. If something breaks at 3am, that's him.",
        },
      ],
      services: ['Web Development', 'UI/UX Design', 'Tech Support'],
    },
    testimonials: {
      heading: 'Reviews',
      items: [
        {
          text: 'A wonderful specialist! He did everything quickly and well. Always stayed in touch and answered all kinds of questions.',
          name: 'Elizaveta',
          role: 'Website',
          initials: 'E',
        },
        {
          text: 'He built a website for watching anime. Dmitry agreed to do everything in the nearest timeframe, which is great!',
          name: 'Denis',
          role: 'Anime site',
          initials: 'D',
        },
        {
          text: 'Excellent specialist! Completed the task within the agreed timeline. Implemented all requests and fixed any issues.',
          name: 'Andrey',
          role: 'Website',
          initials: 'A',
        },
        {
          text: 'He built a ready-made site from my materials and the brief. I received a demo, then paid and got the full version.',
          name: 'Maria',
          role: 'Site from brief',
          initials: 'M',
        },
        {
          text: 'I needed a corporate website with CRM integration. Dmitry delivered perfectly: everything on time, tested, minor feedback addressed.',
          name: 'Sergey',
          role: 'Corporate site',
          initials: 'S',
        },
        {
          text: 'I ordered a landing page for selling handmade goods. He implemented everything exactly to spec and added useful improvement ideas.',
          name: 'Olga',
          role: 'Landing page',
          initials: 'O',
        },
        {
          text: 'He built an online store from scratch. He took into account all my wishes for design and functionality and suggested optimal solutions.',
          name: 'Anna',
          role: 'Online store',
          initials: 'A',
        },
        {
          text: 'I ordered a Telegram bot for taking requests. Dmitry quickly grasped the task and built a bot with an admin panel that is genuinely easy to use.',
          name: 'Pavel',
          role: 'Telegram bot',
          initials: 'P',
        },
        {
          text: 'He refreshed my old site: new design, loads noticeably faster. Search positions did not drop, as I had feared.',
          name: 'Ekaterina',
          role: 'Redesign',
          initials: 'E',
        },
        {
          text: "He picked up the project after another developer. Figured out someone else's code, fixed the bugs and polished everything.",
          name: 'Nikita',
          role: 'Site fixes',
          initials: 'N',
        },
        {
          text: "He built a Tilda landing with custom blocks. It turned out not like everyone else's, and he connected the form to CRM right away.",
          name: 'Victoria',
          role: 'Tilda site',
          initials: 'V',
        },
        {
          text: 'He set up integration with Wildberries and Ozon. Stock now updates itself, I stopped losing orders.',
          name: 'Roman',
          role: 'Integration',
          initials: 'R',
        },
        {
          text: 'I keep my site on a support plan with Dmitry. He replies fast, makes edits the same day, everything under control.',
          name: 'Darya',
          role: 'Site maintenance',
          initials: 'D',
        },
      ],
    },
    faq: {
      heading: 'FAQ',
      items: [
        {
          q: 'How long does a project take?',
          a: "Depends on the scope. A landing page takes 1-2 weeks. A full web app is a month or more. I give you realistic timelines upfront, no lowballing.",
        },
        {
          q: 'Do you work with design or just code?',
          a: "I can work from a Figma file or figure out the design myself. I know what looks good, so it won't just be markup.",
        },
        {
          q: 'How do you handle payment?',
          a: 'Usually 50% upfront, 50% on delivery. For longer projects, monthly. I work officially and can sign a contract.',
        },
        {
          q: 'How do you communicate during the project?',
          a: "Telegram or email. I send updates every few days and show progress along the way. I don't go quiet.",
        },
        {
          q: 'What happens after delivery?',
          a: "There's a support window after delivery. If something comes up, I'll fix it. I can also help with hosting and docs.",
        },
      ],
    },
    contact: {
      sectionLabel: '05 - Contact',
      heading: 'Get in touch',
      subheading: 'Got a project or an idea? Write to me, I reply within the day.',
      form: {
        nameLabel: 'Name', namePlaceholder: 'Your name',
        emailLabel: 'Email', emailPlaceholder: 'your@email.com',
        messageLabel: 'Message', messagePlaceholder: 'Tell me about your project...',
        submitIdle: 'Send', submitSending: 'Sending...', submitSent: '✓ Sent',
        consentBefore: 'I have read the ',
        consentPrivacy: 'Privacy Policy',
        consentMiddle: ' and grant ',
        consentConsent: 'consent to the processing of personal data',
        consentAfter: '.',
        consentRequired: 'You must accept the terms of personal data processing in order to send the message.',
        submitError: 'Could not send. Please try again or message me on Telegram.',
        recaptchaBefore: 'Protected by reCAPTCHA. The Google ',
        recaptchaPrivacy: 'Privacy Policy',
        recaptchaMiddle: ' and ',
        recaptchaTerms: 'Terms of Service',
        recaptchaAfter: ' apply.',
      },
      directLabel: 'Or directly',
      email: shared.socials.email,
      socialsLabel: 'Contacts',
      socials: socialLinks,
      availabilityLabel: 'Availability',
      availabilityText: 'Open to new projects',
    },
    services: {
      heading: 'Services & Pricing',
      subheading: 'Transparent rates for websites, bots and integrations. 2026 market prices.',
      popularBadge: 'Popular',
      currency: '₽',
      thousand: 'k',
      fromLabel: 'from',
      ctaPackage: 'Discuss package',
      tiers: [
        {
          id: 'start',
          name: 'Start',
          priceFrom: 35,
          priceTo: 80,
          tagline: 'Get online fast',
          description: 'When you need to launch a presence quickly - landing page, business card site or simple bot.',
          includes: [
            'Landing page, Tilda site or simple Telegram bot',
            'Up to 5 screens / sections',
            'Mobile-responsive markup',
            'Baseline SEO setup',
            'Domain & analytics setup',
            'Launch in 1–2 weeks',
            '14 days of post-launch support',
          ],
          popular: false,
        },
        {
          id: 'business',
          name: 'Business',
          priceFrom: 80,
          priceTo: 160,
          tagline: 'Optimal choice for growth',
          description: 'Full-fledged corporate site, WordPress shop, or Telegram bot with a web admin panel.',
          includes: [
            'Corporate site (5–15 pages), WP shop or bot with admin',
            'Custom design matching your brand',
            'Extended SEO setup',
            'CRM or payment integration',
            'Analytics and tracking pixels',
            'Launch in 3–6 weeks',
            '30 days of post-launch support',
          ],
          popular: true,
        },
        {
          id: 'premium',
          name: 'Premium',
          priceFrom: 150,
          priceTo: 350,
          tagline: 'Complex projects, end-to-end',
          description: 'Next.js shop, marketplace or platform with integrations and ongoing support.',
          includes: [
            'Next.js shop, marketplace or SaaS platform',
            'Bespoke design + UX research',
            'Integrations: Wildberries, Ozon, 1C, CRM, payments',
            'Extended SEO + schema markup',
            'PageSpeed 90+',
            'Launch in 6–12 weeks',
            '3 months of support + onboarding',
          ],
          popular: false,
        },
      ],
    },
    calculator: {
      heading: 'Estimate your project',
      subheading: 'Ballpark range for your project. Exact figure - after a short brief.',
      typeLabel: 'What do you need',
      pagesLabel: 'Pages / sections count',
      pagesHint: 'Each extra page - +5k ₽',
      designLabel: 'Design',
      extrasLabel: 'Extras',
      resultLabel: 'Estimated cost',
      resultPrefix: 'from',
      resultDivider: 'to',
      currency: '₽',
      thousand: 'k ₽',
      noteTitle: 'This is a preliminary estimate',
      noteText: 'Final price is discussed after a brief. Can go lower if I take the project end-to-end.',
      ctaLabel: 'Get accurate quote',
      resetLabel: 'Reset',
      types: [
        { id: 'landing', label: 'Landing page' },
        { id: 'corporate', label: 'Corporate site' },
        { id: 'shopNext', label: 'Next.js shop' },
        { id: 'shopWp', label: 'WordPress shop' },
        { id: 'tilda', label: 'Tilda site' },
        { id: 'botAdmin', label: 'Bot + admin' },
        { id: 'botSimple', label: 'Simple bot' },
        { id: 'redesign', label: 'Redesign' },
      ],
      designs: [
        { id: 'template', label: 'Ready template', mult: 0.85 },
        { id: 'figma', label: 'Ready Figma design', mult: 1.0 },
        { id: 'custom', label: 'Custom design', mult: 1.3 },
      ],
      extras: [
        { id: 'seo', label: 'Turnkey SEO setup', price: 15000 },
        { id: 'copy', label: 'Copywriting', price: 20000 },
        { id: 'integrations', label: 'Integrations (CRM, payments, marketplaces)', price: 35000 },
        { id: 'multilang', label: 'Multi-language', price: 25000 },
        { id: 'support', label: 'Monthly retainer (1 mo)', price: 30000 },
        { id: 'analytics', label: 'Analytics & pixel setup', price: 10000 },
      ],
    },
    blog: {
      heading: 'Blog',
      subheading: 'I write about development, pricing and tech in plain language. No fluff, no sales.',
      allLabel: 'All articles',
      readLabel: 'Read',
      backLabel: 'All articles',
      homeLabel: 'Home',
      tocLabel: 'Contents',
      faqLabel: 'FAQ',
      relatedLabel: 'Read next',
      ctaTitle: 'Need a site or improvements?',
      ctaText: "I'll walk you through timelines and pricing for your task. I reply within an hour.",
      ctaCalc: 'Estimate cost',
      ctaContact: 'Get in touch',
      indexTitle: 'Blog on website and bot development',
      indexSubheading: 'Articles on pricing, tech and website promotion. Lessons from real projects.',
      minRead: 'min read',
    },
    cookies: {
      heading: 'This site uses cookies',
      text: 'We collect anonymous usage data to understand how to improve the site. By continuing, you agree to the processing of this data.',
      privacyLink: 'Privacy Policy',
      accept: 'Accept',
      decline: 'Decline',
    },
    popup: {
      heading: 'Need a site or improvements?',
      subheading: 'I reply within an hour',
      description: "I'll walk you through timelines, pricing and help pick the stack. No commitment.",
      ctaCalculate: 'Estimate cost',
      ctaTelegram: 'Message on Telegram',
      closeLabel: 'Close',
    },
    floatingCta: {
      label: 'Get a quote',
      shortLabel: 'Quote',
      ariaLabel: 'Open cost calculator',
    },
    footer: {
      author: 'Dmitry Botyan',
      role: 'web developer',
      builtWith: 'React + Vite + RetroUI',
      links: socialLinks,
      legalHeading: 'Legal',
      legalLinks: {
        privacy: 'Privacy Policy',
        terms: 'Terms of Use',
        consent: 'Personal Data Consent',
      },
    },
  },
}

export type Lang = keyof typeof content
export type Content = typeof content.ru

export const calculatorBasePrices: Record<string, [number, number]> = {
  landing:   [45000, 95000],
  corporate: [80000, 160000],
  shopNext:  [120000, 250000],
  shopWp:    [70000, 150000],
  tilda:     [35000, 80000],
  botAdmin:  [45000, 90000],
  botSimple: [15000, 45000],
  redesign:  [40000, 90000],
}
